#pragma once

// GENERATED by firmware/tools/generate_pins.py from docs/PINOUT.md.
// Do not edit this file directly; docs/PINOUT.md is the single source of truth.
#include <Arduino.h>

namespace weather_balloon {
namespace pins {
static constexpr uint8_t kCutdownCtrl = A2;       // J2.4 CUTDOWN_CTRL / PB09
static constexpr uint8_t kOpenLogTx = A1;         // J2.3 UART_TX / PB08
static constexpr uint8_t kOpenLogTxPortGroup = 1; // PB08: PORT group B
static constexpr uint8_t kOpenLogTxPortPin = 8;   // PB08
static constexpr uint8_t kOpenLogSercom = 4;       // SERCOM4
static constexpr uint8_t kOpenLogTxPad = 0;        // PB08 function D / PAD0
static constexpr uint32_t kOpenLogBaud = 9600;     // Qualification default; see DEVPLAN.md
}  // namespace pins
}  // namespace weather_balloon
