#!/usr/bin/env python3
"""Generate firmware/include/pins.h from docs/PINOUT.md.

Run from the repository root. The generator intentionally accepts only the
LightHAB J2 assignments required by this firmware scaffold and fails closed if
the authoritative table changes.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
PINOUT = ROOT / "docs" / "PINOUT.md"
OUTPUT = ROOT / "firmware" / "include" / "pins.h"

text = PINOUT.read_text(encoding="utf-8")
rows = {}
for line in text.splitlines():
    match = re.match(r"\| J2 \| (\d+) \| ([A-Z0-9_]+) \| (.*?) \|$", line)
    if match:
        rows.setdefault((int(match.group(1)), match.group(2)), match.group(3))

uart = rows.get((1, "UART_TX"), "")
led = rows.get((2, "LED_N"), "")
if "A1/PB08" not in uart or "A2/PB09" not in led:
    raise SystemExit("PINOUT.md no longer matches J2.1 UART_TX=A1/PB08 and J2.2 LED_N=A2/PB09; review before regenerating")

header = """#pragma once

// GENERATED by firmware/tools/generate_pins.py from docs/PINOUT.md.
// Do not edit this file directly; docs/PINOUT.md is the single source of truth.
#include <Arduino.h>

namespace weather_balloon {
namespace pins {
static constexpr uint8_t kActivityLed = A2;       // J2.2 LED_N / PB09, active-low
static constexpr uint8_t kOpenLogTx = A1;         // J2.1 UART_TX / PB08
static constexpr uint8_t kOpenLogTxPortGroup = 1; // PB08: PORT group B
static constexpr uint8_t kOpenLogTxPortPin = 8;   // PB08
static constexpr uint8_t kOpenLogSercom = 4;       // SERCOM4
static constexpr uint8_t kOpenLogTxPad = 0;        // PB08 function D / PAD0
static constexpr uint32_t kOpenLogBaud = 9600;     // Qualification default; see DEVPLAN.md
}  // namespace pins
}  // namespace weather_balloon
"""
OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(header, encoding="utf-8")
print(f"generated {OUTPUT.relative_to(ROOT)} from {PINOUT.relative_to(ROOT)}")
